{
 "title": "flowz-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Host", "query": "node_boot_time" },
   { "name": "cluster", "label": "cluster-flowz", "query": "10.42.249.195:9100,none" },
   { "name": "gateway", "label": "api-gateway", "query": "10.42.251.157:9100,none" },
   { "name": "webroot", "label": "web-root", "query": "10.42.131.96:9100,none" },
   { "name": "rethinkdb", "label": "rethinkdb-server", "query": "10.42.134.28:9100,none" },
   { "name": "lblws", "label": "lbl-ws", "query": "10.42.223.109,none" },
   { "name": "prometheus", "label": "prometheus", "query": "10.42.155.126:9100,none" },
   { "name": "front", "label": "front_flowz", "query": "10.42.85.13:9100,none" }
  ]
 },
 "panels": [
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal{instance=~\"$cluster\"} - node_memory_MemAvailable{instance=~\"$cluster\"})*100 /node_memory_MemTotal{instance=~\"$cluster\"}",
     "legendFormat": "cluster-flowz"
    },
    {
     "expr": "(node_memory_MemTotal{instance=~\"$gateway\"} - node_memory_MemAvailable{instance=~\"$gateway\"})*100 /node_memory_MemTotal{instance=~\"$gateway\"}",
     "legendFormat": "api-gateway"
    },
    {
     "expr": "(node_memory_MemTotal{instance=~\"$webroot\"} - node_memory_MemAvailable{instance=~\"$webroot\"})*100 /node_memory_MemTotal{instance=~\"$webroot\"}",
     "legendFormat": "web-root"
    },
    {
     "expr": "(node_memory_MemTotal{instance=~\"$rethinkdb\"} - node_memory_MemAvailable{instance=~\"$rethinkdb\"})*100 /node_memory_MemTotal{instance=~\"$rethinkdb\"}",
     "legendFormat": "rethinkdb"
    },
    {
     "expr": "(node_memory_MemTotal{instance=~\"$lblws\"} - node_memory_MemAvailable{instance=~\"$lblws\"})*100 /node_memory_MemTotal{instance=~\"$lblws\"}",
     "legendFormat": "lbl-ws"
    },
    {
     "expr": "(node_memory_MemTotal{instance=~\"$prometheus\"} - node_memory_MemAvailable{instance=~\"$prometheus\"})*100 /node_memory_MemTotal{instance=~\"$prometheus\"}",
     "legendFormat": "prometheus"
    },
    {
     "expr": "(node_memory_MemTotal{instance=~\"$front\"} - node_memory_MemAvailable{instance=~\"$front\"})*100 /node_memory_MemTotal{instance=~\"$front\"}",
     "legendFormat": "front_flowz"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((avg by (instance)(node_filesystem_size{instance=~\"$cluster\",device=\"/dev/vda1\",fstype=\"ext4\"}))-(avg by (instance)(node_filesystem_free{instance=~\"$cluster\",device=\"/dev/vda1\",fstype=\"ext4\"})))*100/(avg by (instance)(node_filesystem_size{instance=~\"$cluster\",device=\"/dev/vda1\",fstype=\"ext4\"}))",
     "legendFormat": "cluster-flowz"
    },
    {
     "expr": "((avg by (instance)(node_filesystem_size{instance=~\"$gateway\",device=\"/dev/vda1\",fstype=\"ext4\"}))-(avg by (instance)(node_filesystem_free{instance=~\"$gateway\",device=\"/dev/vda1\",fstype=\"ext4\"})))*100/(avg by (instance)(node_filesystem_size{instance=~\"$gateway\",device=\"/dev/vda1\",fstype=\"ext4\"}))",
     "legendFormat": "api-gateway"
    },
    {
     "expr": "((avg by (instance)(node_filesystem_size{instance=~\"$webroot\",device=\"/dev/vda1\",fstype=\"ext4\"}))-(avg by (instance)(node_filesystem_free{instance=~\"$webroot\",device=\"/dev/vda1\",fstype=\"ext4\"})))*100/(avg by (instance)(node_filesystem_size{instance=~\"$webroot\",device=\"/dev/vda1\",fstype=\"ext4\"}))",
     "legendFormat": "web-root"
    },
    {
     "expr": "((avg by (instance)(node_filesystem_size{instance=~\"$rethinkdb\",device=\"/dev/vda1\",fstype=\"ext4\"}))-(avg by (instance)(node_filesystem_free{instance=~\"$rethinkdb\",device=\"/dev/vda1\",fstype=\"ext4\"})))*100/(avg by (instance)(node_filesystem_size{instance=~\"$rethinkdb\",device=\"/dev/vda1\",fstype=\"ext4\"}))",
     "legendFormat": "rethinkdb"
    },
    {
     "expr": "((avg by (instance)(node_filesystem_size{instance=~\"$lblws\",device=\"/dev/vda1\",fstype=\"ext4\"}))-(avg by (instance)(node_filesystem_free{instance=~\"$lblws\",device=\"/dev/vda1\",fstype=\"ext4\"})))*100/(avg by (instance)(node_filesystem_size{instance=~\"$lblws\",device=\"/dev/vda1\",fstype=\"ext4\"}))",
     "legendFormat": "lbl-ws"
    },
    {
     "expr": "((avg by (instance)(node_filesystem_size{instance=~\"$prometheus\",device=\"/dev/vda1\",fstype=\"ext4\"}))-(avg by (instance)(node_filesystem_free{instance=~\"$prometheus\",device=\"/dev/vda1\",fstype=\"ext4\"})))*100/(avg by (instance)(node_filesystem_size{instance=~\"$prometheus\",device=\"/dev/vda1\",fstype=\"ext4\"}))",
     "legendFormat": "prometheus"
    },
    {
     "expr": "((avg by (instance)(node_filesystem_size{instance=~\"$front\",device=\"/dev/vda1\",fstype=\"ext4\"}))-(avg by (instance)(node_filesystem_free{instance=~\"$front\",device=\"/dev/vda1\",fstype=\"ext4\"})))*100/(avg by (instance)(node_filesystem_size{instance=~\"$front\",device=\"/dev/vda1\",fstype=\"ext4\"}))",
     "legendFormat": "front_flowz"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu{instance=~\"$cluster\",mode!=\"idle\"}[60s]))*100",
     "legendFormat": "cluster-flowz"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu{instance=~\"$gateway\",mode!=\"idle\"}[60s]))*100",
     "legendFormat": "api-gateway"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu{instance=~\"$webroot\",mode!=\"idle\"}[60s]))*100",
     "legendFormat": "web-root"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu{instance=~\"$rethinkdb\",mode!=\"idle\"}[60s]))*100",
     "legendFormat": "rethinkdb"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu{instance=~\"$lblws\",mode!=\"idle\"}[60s]))*100",
     "legendFormat": "lbl-ws"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu{instance=~\"$prometheus\",mode!=\"idle\"}[60s]))*100",
     "legendFormat": "prometheus"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu{instance=~\"$front\",mode!=\"idle\"}[60s]))*100",
     "legendFormat": "front_flowz"
    }
   ]
  },
  {
   "title": "Network Traffic In BPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes {device=\"eth0\",instance=~\"$cluster\"}[60s])*100",
     "legendFormat": "cluster-flowz receive_bytes "
    },
    {
     "expr": "irate(node_network_transmit_bytes {device=\"eth0\",instance=~\"$cluster\"}[60s])*100",
     "legendFormat": "cluster-flowz transmit_bytes "
    },
    {
     "expr": "irate(node_network_receive_bytes {device=\"eth0\",instance=~\"$gateway\"}[60s])*100",
     "legendFormat": "api-gateway receive_bytes "
    },
    {
     "expr": "irate(node_network_transmit_bytes {device=\"eth0\",instance=~\"$gateway\"}[60s])*100",
     "legendFormat": "api-gateway transmit_bytes "
    },
    {
     "expr": "irate(node_network_receive_bytes {device=\"eth0\",instance=~\"$webroot\"}[60s])*100",
     "legendFormat": "web-root receive_bytes "
    },
    {
     "expr": "irate(node_network_transmit_bytes {device=\"eth0\",instance=~\"$webroot\"}[60s])*100",
     "legendFormat": "web-root transmit_bytes "
    },
    {
     "expr": "irate(node_network_receive_bytes {device=\"eth0\",instance=~\"$rethinkdb\"}[60s])*100",
     "legendFormat": "rethinkdb receive_bytes "
    },
    {
     "expr": "irate(node_network_transmit_bytes {device=\"eth0\",instance=~\"$rethinkdb\"}[60s])*100",
     "legendFormat": "rethinkdb transmit_bytes "
    },
    {
     "expr": "irate(node_network_receive_bytes {device=\"eth0\",instance=~\"$lblws\"}[60s])*100",
     "legendFormat": "lbl-ws receive_bytes "
    },
    {
     "expr": "irate(node_network_transmit_bytes {device=\"eth0\",instance=~\"$lblws\"}[60s])*100",
     "legendFormat": "lbl-ws transmit_bytes "
    },
    {
     "expr": "irate(node_network_receive_bytes {device=\"eth0\",instance=~\"$prometheus\"}[60s])*100",
     "legendFormat": "prometheus receive_bytes "
    },
    {
     "expr": "irate(node_network_transmit_bytes {device=\"eth0\",instance=~\"$prometheus\"}[60s])*100",
     "legendFormat": "prometheus transmit_bytes "
    },
    {
     "expr": "irate(node_network_receive_bytes {device=\"eth0\",instance=~\"$front\"}[60s])*100",
     "legendFormat": "front_flowz receive_bytes "
    },
    {
     "expr": "irate(node_network_transmit_bytes {device=\"eth0\",instance=~\"$front\"}[60s])*100",
     "legendFormat": "front_flowz transmit_bytes "
    }
   ]
  },
  {
   "title": "Network Traffic In PPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$cluster\",device=\"eth0\"}[60s])*100",
     "legendFormat": "cluster-flowz receive_packets "
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$cluster\",device=\"eth0\"}[60s])*100",
     "legendFormat": "cluster-flowz transmit_packets "
    },
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$gateway\",device=\"eth0\"}[60s])*100",
     "legendFormat": "api-gateway receive_packets "
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$gateway\",device=\"eth0\"}[60s])*100",
     "legendFormat": "api-gateway transmit_packets "
    },
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$webroot\",device=\"eth0\"}[60s])*100",
     "legendFormat": "web-root receive_packets "
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$webroot\",device=\"eth0\"}[60s])*100",
     "legendFormat": "web-root transmit_packets "
    },
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$rethinkdb\",device=\"eth0\"}[60s])*100",
     "legendFormat": "rethinkdb receive_packets "
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$rethinkdb\",device=\"eth0\"}[60s])*100",
     "legendFormat": "rethinkdb transmit_packets "
    },
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$prometheus\",device=\"eth0\"}[60s])*100",
     "legendFormat": "prometheus receive_packets "
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$prometheus\",device=\"eth0\"}[60s])*100",
     "legendFormat": "prometheus transmit_packets "
    },
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$front\",device=\"eth0\"}[60s])*100",
     "legendFormat": "front_flowz receive_packets "
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$front\",device=\"eth0\"}[60s])*100",
     "legendFormat": "front_flowz transmit_packets "
    }
   ]
  }
 ]
}