{
 "title": "MY-SQL monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node_exporter", "label": "node_exporter", "query": "10.42.88.242:9100" },
   { "name": "cadvisor", "label": "cadvisor", "query": "10.42.173.211:8080" }
  ]
 },
 "panels": [
  { "title": "Basic Info.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rancher_host_state{name=\"flz-master-database-mysql\"} > 0",
     "legendFormat": "Host Status"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=\"$cadvisor\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu{instance=~\"$node_exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total Hard-Disk",
   "type": "singlestat",
   "description": "Total Hard-Disk In Host",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size{instance=\"$node_exporter\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Used Hard-Disk",
   "type": "singlestat",
   "description": "Used Hard-Disk in Host",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size{instance=\"$node_exporter\", mountpoint=\"/\"} - node_filesystem_free{instance=\"$node_exporter\", mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Free Hard-Disk",
   "type": "singlestat",
   "description": "Free Hard-Disk in Host",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_free{instance=\"$node_exporter\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total Memory In Host",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{instance=\"$node_exporter\" })/1024/1024"
    }
   ]
  },
  {
   "title": "CPU / Memory / Hard-Disk Info.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Hard-Disk Used",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "((node_filesystem_size{instance=\"$node_exporter\", mountpoint=\"/\"} - node_filesystem_free{instance=\"$node_exporter\", mountpoint=\"/\"})*100 )/ node_filesystem_size{instance=\"$node_exporter\", mountpoint=\"/\"} "
      }
     ]
    },
    {
     "title": "Host CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(node_cpu{instance=\"$node_exporter\" ,mode!=\"idle\"}[5m]) * 100)"
      }
     ]
    },
    {
     "title": "Host Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "((node_memory_MemTotal{instance=\"$node_exporter\"} - node_memory_MemFree{instance=\"$node_exporter\"} - node_memory_Cached{instance=~\"$node_exporter\"}) / (node_memory_MemTotal{instance=~\"$node_exporter\"} )) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_cpu{instance=\"10.42.88.242:9100\" , mode!=\"idle\"}[5m])) * 100 ",
       "legendFormat": "MYSQL Host"
      },
      {
       "expr": "rate(container_cpu_user_seconds_total{instance=\"$cadvisor\" ,image=\"mysql:5.6\"}[5m]) * 100",
       "legendFormat": "db-1"
      },
      {
       "expr": "rate(container_cpu_user_seconds_total{instance=\"$cadvisor\" ,image=\"phpmyadmin/phpmyadmin\"}[5m]) * 100",
       "legendFormat": "mysqladmin-1"
      },
      {
       "expr": "rate(container_cpu_user_seconds_total{instance=\"$cadvisor\" ,image=\"postgres\"}[5m]) * 100",
       "legendFormat": "postgres"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage( In %)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_memory_MemTotal{instance=\"10.42.88.242:9100\"} - node_memory_MemFree{instance=\"10.42.88.242:9100\"} - node_memory_Cached{instance=~\"10.42.88.242:9100\"}) / (node_memory_MemTotal{instance=~\"10.42.88.242:9100\"} )) * 100",
       "legendFormat": "My-Sql"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal{instance=\"$node_exporter\"} - node_memory_MemFree{instance=\"$node_exporter\"} - node_memory_Cached{instance=~\"$node_exporter\"}",
       "legendFormat": "My-Sql"
      },
      {
       "expr": "container_memory_usage_bytes{instance=\"$cadvisor\",image=\"mysql:5.6\"} - container_memory_cache{instance=\"$cadvisor\",image=\"mysql:5.6\"} ",
       "legendFormat": "db-1"
      },
      {
       "expr": "container_memory_usage_bytes{instance=\"$cadvisor\", image=\"phpmyadmin/phpmyadmin\"} - container_memory_cache{instance=\"$cadvisor\", image=\"phpmyadmin/phpmyadmin\"} ",
       "legendFormat": "mysqladmin-1"
      },
      {
       "expr": "container_memory_usage_bytes{instance=\"$cadvisor\", image=\"postgres\"} - container_memory_cache{instance=\"$cadvisor\", image=\"postgres\"} ",
       "legendFormat": "postgres"
      }
     ]
    }
   ]
  },
  {
   "title": "FileSystem Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "File System",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_filesystem_size{instance=\"10.42.88.242:9100\", mountpoint=\"/\"} - node_filesystem_free{instance=\"10.42.88.242:9100\", mountpoint=\"/\"})*100 )/ node_filesystem_size{instance=\"10.42.88.242:9100\", mountpoint=\"/\"} ",
       "legendFormat": "used hard disk"
      }
     ]
    },
    {
     "title": "File System Used By Container",
     "type": "graph",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_usage_bytes{instance=\"$cadvisor\", image=\"mysql:5.6\"}",
       "legendFormat": "db-1"
      },
      {
       "expr": "container_fs_usage_bytes{instance=\"$cadvisor\", image=\"phpmyadmin/phpmyadmin\"}",
       "legendFormat": "mysqladmin-1"
      },
      {
       "expr": "container_fs_usage_bytes{instance=\"$cadvisor\", image=\"postgres\"}",
       "legendFormat": "postgres"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Rx Bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{instance=\"$cadvisor\"}[30s])) * 8",
       "legendFormat": "HOST"
      },
      {
       "expr": "rate(container_network_receive_bytes_total{instance=\"$cadvisor\" ,image=\"mysql:5.6\"}[30s]) * 8",
       "legendFormat": "db"
      },
      {
       "expr": "rate(container_network_receive_bytes_total{instance=\"$cadvisor\" ,image=\"phpmyadmin/phpmyadmin\"}[30s]) * 8",
       "legendFormat": "mysql-admin"
      }
     ]
    },
    {
     "title": "Network Tx Bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"$cadvisor\"}[5m])) * 8",
       "legendFormat": "HOST"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{instance=\"$cadvisor\" ,image=\"mysql:5.6\"}[5m]) * 8",
       "legendFormat": "db"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{instance=\"$cadvisor\" ,image=\"phpmyadmin/phpmyadmin\"}[5m]) * 8",
       "legendFormat": "mysql-admin"
      }
     ]
    }
   ]
  }
 ]
}